// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh6uH1oD5XUNB4fzssVG991tUuCp5vqYQ',
    appId: '1:69047120729:web:32b96eb92ff6f886a79248',
    messagingSenderId: '69047120729',
    projectId: 'services-e8b07',
    authDomain: 'services-e8b07.firebaseapp.com',
    storageBucket: 'services-e8b07.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE3CEW3kTZK5LxNN_qjLWCH4rx4A_2ues',
    appId: '1:69047120729:android:9f24bd5bba8f6da2a79248',
    messagingSenderId: '69047120729',
    projectId: 'services-e8b07',
    storageBucket: 'services-e8b07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7-_uweVZTLWfXsMDP6elA5fnqxhYY_oI',
    appId: '1:69047120729:ios:c26724b15afe8c94a79248',
    messagingSenderId: '69047120729',
    projectId: 'services-e8b07',
    storageBucket: 'services-e8b07.appspot.com',
    iosBundleId: 'com.example.services',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7-_uweVZTLWfXsMDP6elA5fnqxhYY_oI',
    appId: '1:69047120729:ios:c26724b15afe8c94a79248',
    messagingSenderId: '69047120729',
    projectId: 'services-e8b07',
    storageBucket: 'services-e8b07.appspot.com',
    iosBundleId: 'com.example.services',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCh6uH1oD5XUNB4fzssVG991tUuCp5vqYQ',
    appId: '1:69047120729:web:371d4d74d41d7d54a79248',
    messagingSenderId: '69047120729',
    projectId: 'services-e8b07',
    authDomain: 'services-e8b07.firebaseapp.com',
    storageBucket: 'services-e8b07.appspot.com',
  );
}
